import Feed from '@/components/Feed';
import Header from '@/components/Header';
import Modal from '@/components/Modal';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>

      <Header />
      <Feed />

      {/* Modal */}
      <Modal />
    </>
  );
}
